### ISSUE TITLE
Unable to download Dailymotion video

### ISSUE THREAD

**Issue by sriniprash** [isync/www-dailymotion-download#3]
When i run this command,

perl dailymotion-download http://www.dailymotion.com/video/kKq4YLbGAQz1c0aEF8T

I get the following error:

Downloading http://www.dailymotion.com/video/kKq4YLbGAQz1c0aEF8T
Could not get video id! at lib/WWW/Dailymotion/Download.pm line 28.

**Comment by isync** [comment]
I know, currently it's not working. See my last commit message ("nearly fixed") - where I worked towards making it works again, and failed without much bigger effort.

Feel free to fork and fix or send a patch.

Don't know when I find the time to work on it again.

**Comment by isync** [comment]
I've restored it to working state again, and this time it's able to download the highest quality, HD videos.
Case closed.

**Comment by DrNossberg** [comment]
Doesn't work 
The code is looking of an "id" in the URL, and the programme stop when unable to find it (moste dailymotion video doesn't have "id=" in URL anymore)
Nice code tho
